service: my-rest-api-service2

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: arn:aws:s3:::my-bucket/*

functions:
  app:
    handler: dist/main.start
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
    code:
      S3Bucket: my-s3-bucket
      S3Key: my-function-code.zip
